name: Docker Image CI

on:
  push:
    branches: [ "dev","master" ]
  pull_request:
    branches: [ "dev" ,"master"]
env: 
  DOCKER_NAME: blkhrt225
  DOCKER_TOKEN: ef55a328-fa2a-4b7b-b1f0-a560e8fea288
  IMAGE: blkhrt225/docker-test
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{env.DOCKER_NAME}}
        password: ${{env.DOCKER_TOKEN}}
        
    - name: Build the Docker image Dev
      if: ${{ github.ref == 'refs/heads/dev' }}
      run: echo "Hello Dev"
    - name: Build the Docker Image Master
      if: ${{github.ref == 'refs/heads/master'}}
      run: echo "Hello Master"
      
 
             
            
           
     
     
